### ISSUE TITLE
ConsentException when running ctera_filer_first_user

### ISSUE THREAD

**Issue by mgaruccio** [ctera/ctera-ansible-collections#32]
I am attempting to run the `ctera_filer_first_user` module against a newly deployed ctera device and getting the a `ConsentException`. I did validate that I'm able to apply the same password I'm attempting to use for the filer if I use it via the UI instead of the ansible module.

module invocation - 

```yaml
    - name: configure ctera first user
      ctera.ctera.ctera_filer_first_user:
        ctera_host: "{{ virtual_machine.instance.ipv4 }}"
        ctera_user: admin
        ctera_password: "{{ new_filer_password }}"
```

error message - 

```yaml
fatal: [localhost]: FAILED! => changed=false 
  invocation:
    module_args:
      ctera_host: 10.181.223.63
      ctera_https: true
      ctera_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      ctera_port: null
      ctera_trust_certificate: false
      ctera_user: admin
      email: null
  msg: 'First user management failed Exception: {"classname": "ConsentException", "message": "Every decision is liberating, even if it leads to disaster"}'
```
